/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Event;
import classes.Operator;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.DefaultListModel;

/**
 *
 * @author nilss
 */
public class FrmEvent extends javax.swing.JPanel {

    private Event event = null;

    /**
     * Creates new form FrmEvent
     */
    public FrmEvent() {
        initComponents();
    }

    public void setEvent(Event event) {
        if (event != null) {
            this.event = event;

            txtEventName.setText(this.event.getName());
            dtPicker.datePicker.setDate(LocalDate.of(this.event.getDate().getYear(), this.event.getDate().getMonth(), this.event.getDate().getDayOfMonth()));
            dtPicker.timePicker.setTime(LocalTime.of(this.event.getDate().getHour(), this.event.getDate().getMinute()));
            txtEventDuration.setText(String.valueOf(this.event.getDuration()));
            txtEventLocation.setText(this.event.getLocation());

            switch (this.event.getPriority()) {
                case LOW:
                    cbEventNotification.getModel().setSelectedItem("low");
                    break;
                case MEDIUM:
                    cbEventNotification.getModel().setSelectedItem("medium");
                    break;
                case HIGH:
                    cbEventNotification.getModel().setSelectedItem("high");
                    break;
            }

            switch (this.event.getNotification()) {
                case NONE:
                    cbEventNotification.getModel().setSelectedItem("none");
                    break;
                case TEN_MINUTES:
                    cbEventNotification.getModel().setSelectedItem("10 minutes");
                    break;
                case ONE_HOUR:
                    cbEventNotification.getModel().setSelectedItem("1 hour");
                    break;
                case THREE_DAYS:
                    cbEventNotification.getModel().setSelectedItem("3 days");
                    break;
                case ONE_WEEK:
                    cbEventNotification.getModel().setSelectedItem("1 week");
                    break;
            }

            javax.swing.DefaultListModel<Operator> liModelParticipants = new DefaultListModel();
            for (int i = 0; i < this.event.getParticipants().size(); i++) {
                liModelParticipants.addElement(this.event.getParticipants().get(i));
            }

            javax.swing.DefaultListModel<String> liModelAttachments = new DefaultListModel();
            for (int i = 0; i < this.event.getAttachments().size(); i++) {
                liModelAttachments.addElement(this.event.getAttachments().get(i).getName());
            }

        }
    }

    public Event getEvent() {
        
        
        return this.event;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeadline = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        lblEventName = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        lblDateTime = new javax.swing.JLabel();
        dtPicker = new com.github.lgooddatepicker.components.DateTimePicker();
        lblEventDuration = new javax.swing.JLabel();
        txtEventDuration = new javax.swing.JTextField();
        lblEventLocation = new javax.swing.JLabel();
        txtEventLocation = new javax.swing.JTextField();
        lblEventPriority = new javax.swing.JLabel();
        cbEventPriority = new javax.swing.JComboBox<>();
        lblEventNotification = new javax.swing.JLabel();
        cbEventNotification = new javax.swing.JComboBox<>();
        lblEventPArticipants = new javax.swing.JLabel();
        pnlEventParticipants = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        lblEventAttachments = new javax.swing.JLabel();
        pnlEventAttachments = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        pnlFooter = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(200, 300));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setPreferredSize(new java.awt.Dimension(400, 30));
        pnlHeader.setLayout(new java.awt.BorderLayout());
        pnlHeader.add(lblHeadline, java.awt.BorderLayout.CENTER);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlContent.setLayout(new javax.swing.BoxLayout(pnlContent, javax.swing.BoxLayout.Y_AXIS));

        lblEventName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEventName.setText("Name:");
        lblEventName.setToolTipText("");
        pnlContent.add(lblEventName);
        pnlContent.add(txtEventName);

        lblDateTime.setText("Date:");
        pnlContent.add(lblDateTime);
        pnlContent.add(dtPicker);

        lblEventDuration.setText("Duration");
        pnlContent.add(lblEventDuration);
        pnlContent.add(txtEventDuration);

        lblEventLocation.setText("Location");
        pnlContent.add(lblEventLocation);
        pnlContent.add(txtEventLocation);

        lblEventPriority.setText("Priority");
        pnlContent.add(lblEventPriority);

        cbEventPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "low", "medium", "high" }));
        pnlContent.add(cbEventPriority);

        lblEventNotification.setText("Notification:");
        pnlContent.add(lblEventNotification);

        cbEventNotification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "10 minutes", "1 hour", "3 days", "1 week" }));
        pnlContent.add(cbEventNotification);

        lblEventPArticipants.setText("Participants:");
        pnlContent.add(lblEventPArticipants);

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout pnlEventParticipantsLayout = new javax.swing.GroupLayout(pnlEventParticipants);
        pnlEventParticipants.setLayout(pnlEventParticipantsLayout);
        pnlEventParticipantsLayout.setHorizontalGroup(
            pnlEventParticipantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventParticipantsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlEventParticipantsLayout.setVerticalGroup(
            pnlEventParticipantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventParticipantsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEventParticipantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEventParticipantsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlContent.add(pnlEventParticipants);

        lblEventAttachments.setText("Attachments:");
        pnlContent.add(lblEventAttachments);

        jButton2.setText("jButton2");

        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout pnlEventAttachmentsLayout = new javax.swing.GroupLayout(pnlEventAttachments);
        pnlEventAttachments.setLayout(pnlEventAttachmentsLayout);
        pnlEventAttachmentsLayout.setHorizontalGroup(
            pnlEventAttachmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventAttachmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        pnlEventAttachmentsLayout.setVerticalGroup(
            pnlEventAttachmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventAttachmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEventAttachmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContent.add(pnlEventAttachments);

        add(pnlContent, java.awt.BorderLayout.CENTER);

        pnlFooter.setLayout(new java.awt.GridLayout());

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-bin-line.png"))); // NOI18N
        btnDelete.setText("Delete");
        pnlFooter.add(btnDelete);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-line.png"))); // NOI18N
        btnOk.setText("Ok");
        pnlFooter.add(btnOk);

        add(pnlFooter, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbEventNotification;
    private javax.swing.JComboBox<String> cbEventPriority;
    private com.github.lgooddatepicker.components.DateTimePicker dtPicker;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblEventAttachments;
    private javax.swing.JLabel lblEventDuration;
    private javax.swing.JLabel lblEventLocation;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblEventNotification;
    private javax.swing.JLabel lblEventPArticipants;
    private javax.swing.JLabel lblEventPriority;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlEventAttachments;
    private javax.swing.JPanel pnlEventParticipants;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTextField txtEventDuration;
    private javax.swing.JTextField txtEventLocation;
    private javax.swing.JTextField txtEventName;
    // End of variables declaration//GEN-END:variables
}
