/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import EventUtilities.EventsOfDayListModel;
import classes.Event;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author nilss
 */
public class FrmEventsOfDay extends javax.swing.JPanel {

    /**
     * Creates new form FrmEventsOfDay
     */
    public FrmEventsOfDay(ArrayList<Event> eventsOfDay) {
        initComponents();
        
        liEventsOfDay.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setEventds(eventsOfDay);
    }

    
    
    public void setEventds(ArrayList<Event> eventsOfDay) {
        if (eventsOfDay != null) {
            EventsOfDayListModel liModelEventsOfDay = new EventsOfDayListModel();
            liModelEventsOfDay.addElement(eventsOfDay);

            liEventsOfDay.setModel((ListModel)liModelEventsOfDay);
        }
    }

    private void displayEventDetail(Event selectedEvent) {
        JDialog dialog = new JDialog();
        
        dialog.setSize(500, 700);
        dialog.setModal(true);
        dialog.add(new FrmEvent(null));
        dialog.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblHeadline = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liEventsOfDay = new javax.swing.JList<>();
        pnlFooter = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlHeader.setPreferredSize(new java.awt.Dimension(313, 45));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblHeadline.setText("Your daily appointments:");
        pnlHeader.add(lblHeadline, java.awt.BorderLayout.CENTER);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlContent.setLayout(new java.awt.BorderLayout());

        liEventsOfDay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        liEventsOfDay.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liEventsOfDayValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(liEventsOfDay);

        pnlContent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlContent, java.awt.BorderLayout.CENTER);

        pnlFooter.setPreferredSize(new java.awt.Dimension(313, 45));

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar-2-line.png"))); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setPreferredSize(new java.awt.Dimension(95, 35));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pnlFooter, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void liEventsOfDayValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liEventsOfDayValueChanged
        
    }//GEN-LAST:event_liEventsOfDayValueChanged

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        //Event selectedEvent = liEventsOfDay.getModel().getElementAt(0);
        //displayEventDetail();
    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeadline;
    private javax.swing.JList<String> liEventsOfDay;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
